name: paumaso
favicon: null
layout_spectrum: 0.7396144967060536
typography_spectrum: 0.36814
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#0e0a07'
    - '#781523'
    - '#b48578'
    - '#514039'
  brandStrength: 0.3125
  lightness: 0.6429969368036836
  saturation: 0.4506362327374518
  rhythmicContrast: 0.40530354157090187
purpose: []
