name: paumaso
favicon: null
layout_spectrum: 0.7396144967060536
typography_spectrum: 0.006696752971038222
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3310833997093141
  lightness: 0.6429969368036836
  saturation: 0.4506362327374518
  rhythmicContrast: 0.40530354157090187
purpose: []
