name: paumaso
favicon: null
layout_spectrum: 0.8395
typography_spectrum: 0.89917
title: Pau Masó
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a222f'
    - '#d4c165'
    - '#c6945c'
    - '#8d5743'
    - '#9daf8c'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.4053035415709019
purpose: []
